[package]
name = "OilTracker"
version = "1.0.0"

[addresses]
oil_tracker = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
